### ISSUE TITLE
no --tool-change ?

### ISSUE THREAD

**Issue by yrabbit** [fra589/grbl_post#2]
Hello,
what about the --tool-change argument?

**Comment by fra589** [comment]
Hi, @yrabbit,  
Since M6 tool change is not actually supported by Grbl, I did not find it useful to keep this argument.  
However, there is the OUTPUT_TOOL_CHANGE customization variable which defaults to False which can be activated to True if you have a modified Grbl that supports the M6 command.  
It is possible that later, this argument will comes back because I intend to add the tool change management in my grbl-Mega-5X version.  
@++;  
Gauthier.
