### ISSUE TITLE
Fusion 360 Post

### ISSUE THREAD

**Issue by EragonPower** [fra589/grbl_post#3]
I've used GRBL 5X in combination with Fusion360 for quite a while now and i was wandering, does exist a grbl post processor for Fusion360? Apparently for now a post processor for GRBL 5X hasn't been created yet, so, can you made one? 
Following is the post processor for GRBL that Fusion360 gives, maybe it can be usefull as starting point. (It's zipped only because github doesn't supports .cps files)
[grbl.zip](https://github.com/fra589/grbl_post/files/3865352/grbl.zip)

**Comment by fra589** [comment]
Hello @EragonPower,

grbl_post is an open source post processor wich ensure communication between 2 others greats open source software : FreeCAD and Grbl*.

Since Fusion 360 is not an open source software, ask to Autodesk to make this post processor or use full open source CAD / CAM software chain...

@++;  
Gauthier.
